export const colors = {  
  brand: {
    1: "var(--color-brand-1)",
    2: "var(--color-brand-2)",
    3: "var(--color-brand-3)",
    4: "var(--color-brand-4)",
    5: "var(--color-brand-5)",
    6: "var(--color-brand-6)",
    7: "var(--color-brand-7)",
    8: "var(--color-brand-8)",
    9: "var(--color-brand-9)",
    transparent: "var(--color-brand-transparent)",
    extraTransparent: "var(--color-brand-extra-transparent)",
  },
  red: {
    1: "var(--color-red-1)",
    2: "var(--color-red-2)",
    3: "var(--color-red-3)",
    4: "var(--color-red-4)",
    5: "var(--color-red-5)",
    6: "var(--color-red-6)",
    7: "var(--color-red-7)",
    8: "var(--color-red-8)",
    9: "var(--color-red-9)",
    transparent: "var(--color-red-transparent)",
    extraTransparent: "var(--color-red-extra-transparent)",
  },
  orange: {
    1: "var(--color-orange-1)",
    2: "var(--color-orange-2)",
    3: "var(--color-orange-3)",
    4: "var(--color-orange-4)",
    5: "var(--color-orange-5)",
    6: "var(--color-orange-6)",
    7: "var(--color-orange-7)",
    8: "var(--color-orange-8)",
    9: "var(--color-orange-9)",
    transparent: "var(--color-orange-transparent)",
    extraTransparent: "var(--color-orange-extra-transparent)",
  },
  yellow: {
    1: "var(--color-yellow-1)",
    2: "var(--color-yellow-2)",
    3: "var(--color-yellow-3)",
    4: "var(--color-yellow-4)",
    5: "var(--color-yellow-5)",
    6: "var(--color-yellow-6)",
    7: "var(--color-yellow-7)",
    8: "var(--color-yellow-8)",
    9: "var(--color-yellow-9)",
    transparent: "var(--color-yellow-transparent)",
    extraTransparent: "var(--color-yellow-extra-transparent)",
  },
  green: {
    1: "var(--color-green-1)",
    2: "var(--color-green-2)",
    3: "var(--color-green-3)",
    4: "var(--color-green-4)",
    5: "var(--color-green-5)",
    6: "var(--color-green-6)",
    7: "var(--color-green-7)",
    8: "var(--color-green-8)",
    9: "var(--color-green-9)",
    transparent: "var(--color-green-transparent)",
    extraTransparent: "var(--color-green-extra-transparent)",
  },
  sky: {
    1: "var(--color-sky-1)",
    2: "var(--color-sky-2)",
    3: "var(--color-sky-3)",
    4: "var(--color-sky-4)",
    5: "var(--color-sky-5)",
    6: "var(--color-sky-6)",
    7: "var(--color-sky-7)",
    8: "var(--color-sky-8)",
    9: "var(--color-sky-9)",
    transparent: "var(--color-sky-transparent)",
    extraTransparent: "var(--color-sky-extra-transparent)",
  },
  blue: {
    1: "var(--color-blue-1)",
    2: "var(--color-blue-2)",
    3: "var(--color-blue-3)",
    4: "var(--color-blue-4)",
    5: "var(--color-blue-5)",
    6: "var(--color-blue-6)",
    7: "var(--color-blue-7)",
    8: "var(--color-blue-8)",
    9: "var(--color-blue-9)",
    transparent: "var(--color-blue-transparent)",
    extraTransparent: "var(--color-blue-extra-transparent)",
  },
  purple: {
    1: "var(--color-purple-1)",
    2: "var(--color-purple-2)",
    3: "var(--color-purple-3)",
    4: "var(--color-purple-4)",
    5: "var(--color-purple-5)",
    6: "var(--color-purple-6)",
    7: "var(--color-purple-7)",
    8: "var(--color-purple-8)",
    9: "var(--color-purple-9)",
    transparent: "var(--color-purple-transparent)",
    extraTransparent: "var(--color-purple-extra-transparent)",
  },
  magenta: {
    1: "var(--color-magenta-1)",
    2: "var(--color-magenta-2)",
    3: "var(--color-magenta-3)",
    4: "var(--color-magenta-4)",
    5: "var(--color-magenta-5)",
    6: "var(--color-magenta-6)",
    7: "var(--color-magenta-7)",
    8: "var(--color-magenta-8)",
    9: "var(--color-magenta-9)",
    transparent: "var(--color-magenta-transparent)",
    extraTransparent: "var(--color-magenta-extra-transparent)",
  },
  gray: {
    1: "var(--color-gray-1)",
    2: "var(--color-gray-2)",
    3: "var(--color-gray-3)",
    4: "var(--color-gray-4)",
    5: "var(--color-gray-5)",
    6: "var(--color-gray-6)",
    7: "var(--color-gray-7)",
    8: "var(--color-gray-8)",
    9: "var(--color-gray-9)",
    transparent: "var(--color-gray-transparent)",
    extraTransparent: "var(--color-gray-extra-transparent)",
  },
  body: 'var(--color-body)',
  bodyAlt: 'var(--color-body-alt)',
  bodyText: 'var(--color-body-text)',
  bodyTextAlt: 'var(--color-body-text-alt)',
  shadow: 'var(--color-shadow)',
  outline: 'var(--color-outline)',
};

export const fontSizes = {
  