name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-stylesheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./packages/stylesheet
      - run: npm run lint
        working-directory: ./packages/stylesheet
      - run: npm run build
        working-directory: ./packages/stylesheet
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./packages/stylesheet-docs
      - run: npm run build
        working-directory: ./packages/stylesheet-docs
